package com.jsd.aird.shared.error;

public enum ApiErrorCode {

    VALIDATION_ERROR("SYS_VALIDATION_ERROR", "请求参数校验失败", 422),
    BAD_REQUEST("SYS_BAD_REQUEST", "请求内容无法解析", 400),
    NOT_FOUND("SYS_NOT_FOUND", "资源不存在", 404),
    RESOURCE_CONFLICT("RESOURCE_CONFLICT", "资源已存在或发生冲突", 409),
    REFERENCE_IN_USE("REFERENCE_IN_USE", "活动资料参考仍在使用该项目关联", 409),
    OPERATION_FORBIDDEN("OPERATION_FORBIDDEN", "当前身份无权执行此操作", 403),
    AUTH_REQUIRED("AUTH_REQUIRED", "请先登录", 401),
    AUTH_INVALID("AUTH_INVALID", "用户名或密码错误", 401),
    ACCOUNT_DISABLED("ACCOUNT_DISABLED", "账号已停用", 403),
    ACCOUNT_LOCKED("ACCOUNT_LOCKED", "账号暂时锁定，请稍后再试", 423),
    AUTH_RATE_LIMITED("AUTH_RATE_LIMITED", "登录请求过于频繁，请稍后再试", 429),
    CSRF_TOKEN_INVALID("CSRF_TOKEN_INVALID", "页面安全令牌已失效，请刷新页面后重试", 403),
    PERMISSION_DENIED("PERMISSION_DENIED", "当前用户没有执行该操作的权限", 403),
    DATA_SCOPE_DENIED("DATA_SCOPE_DENIED", "当前用户没有访问该数据范围的权限", 403),
    AI_EXTERNAL_NOT_ALLOWED("AI_EXTERNAL_NOT_ALLOWED", "当前资源未授权 AI 外发", 403),
    POLICY_VERSION_CONFLICT("POLICY_VERSION_CONFLICT", "权限策略已被其他管理员更新，请刷新后重试", 409),
    DEV_IDENTITY_FORBIDDEN("DEV_IDENTITY_FORBIDDEN", "生产环境禁止使用开发身份请求头", 403),
    INVALID_SCHEMA("INVALID_SCHEMA", "Schema、Mapping 或命令结构非法", 400),
    OPTIMISTIC_LOCK_CONFLICT("OPTIMISTIC_LOCK_CONFLICT", "草稿已被其他会话更新", 409),
    TEMPLATE_VERSION_IMMUTABLE("TEMPLATE_VERSION_IMMUTABLE", "发布或停用版本不可修改", 409),
    RECOGNITION_UNCONFIRMED("RECOGNITION_UNCONFIRMED", "仍有未确认的识别建议", 422),
    BINDING_INVALID("BINDING_INVALID", "Mapping 存在失效或冲突绑定", 422),
    REVIEW_REQUIRED("REVIEW_REQUIRED", "模板必须审核通过后才能发布", 422),
    REVIEW_REASON_REQUIRED("REVIEW_REASON_REQUIRED", "驳回原因不能为空", 422),
    REVIEW_STATE_CONFLICT("REVIEW_STATE_CONFLICT", "模板审核状态不允许当前操作", 409),
    TEMPLATE_REQUIRED_FIELD_UNBOUND("TEMPLATE_REQUIRED_FIELD_UNBOUND", "存在必填字段未绑定位置", 422),
    TEMPLATE_FIELD_LOCATOR_INVALID("TEMPLATE_FIELD_LOCATOR_INVALID", "字段定位信息无效", 422),
    TEMPLATE_FIELD_LABEL_UNRESOLVED("TEMPLATE_FIELD_LABEL_UNRESOLVED", "存在字段尚未确认标签位置", 422),
    TEMPLATE_EXPERIMENT_SEMANTICS_INVALID(
            "TEMPLATE_EXPERIMENT_SEMANTICS_INVALID",
            "实验模板语义配置无效",
            422
    ),
    EXPERIMENT_TEMPLATE_REQUIRED(
            "EXPERIMENT_TEMPLATE_REQUIRED",
            "当前AI任务未配置可用的已发布实验模板",
            422
    ),
    TEMPLATE_REQUIRED_VALUE_MISSING("TEMPLATE_REQUIRED_VALUE_MISSING", "存在必填字段未填写", 422),
    DATA_SCHEMA_INVALID("DATA_SCHEMA_INVALID", "业务数据不符合 Schema", 422),
    WORKBOOK_DATA_DIVERGED("WORKBOOK_DATA_DIVERGED", "编辑器值与 JSONB 值不一致，需要显式协调", 422),
    MAPPING_RECONCILIATION_REQUIRED(
            "MAPPING_RECONCILIATION_REQUIRED",
            "结构编辑后存在失效或歧义绑定，需要协调",
            422
    ),
    SNAPSHOT_VERSION_UNSUPPORTED(
            "SNAPSHOT_VERSION_UNSUPPORTED",
            "当前运行时无法安全加载该编辑器快照",
            422
    ),
    FILE_NOT_READY("FILE_NOT_READY", "快照或源文件尚未激活", 423),
    KNOWLEDGE_NOT_READY("KNOWLEDGE_NOT_READY", "知识文件尚未完成解析", 423),
    AI_NOT_CONFIGURED("AI_NOT_CONFIGURED", "AI 模型尚未配置", 503),
    AI_MODEL_NOT_CONFIGURED("AI_MODEL_NOT_CONFIGURED", "AI 模型网关尚未配置，请联系管理员检查模型服务配置", 503),
    AI_DOCUMENT_NOT_APPROVED("AI_DOCUMENT_NOT_APPROVED", "文件尚未获得 AI 使用授权", 422),
    AI_PERMISSION_DENIED("AI_PERMISSION_DENIED", "当前用户没有使用 AI 问答的权限", 403),
    AI_MODEL_AUTH_FAILED("AI_MODEL_AUTH_FAILED", "AI 模型服务认证失败，请联系管理员检查模型网关配置", 503),
    AI_MODEL_RATE_LIMITED("AI_MODEL_RATE_LIMITED", "AI 模型服务请求过于频繁，请稍后重试", 429),
    AI_MODEL_TIMEOUT("AI_MODEL_TIMEOUT", "AI 模型服务响应超时，请稍后重试", 504),
    AI_MODEL_EMPTY_RESPONSE("AI_MODEL_EMPTY_RESPONSE", "AI 模型未返回有效回答，请稍后重试", 503),
    AI_MODEL_ARTIFACT_INVALID("AI_MODEL_ARTIFACT_INVALID", "活动配方模型制品无效或版本不兼容", 503),
    VERSION_CONFLICT("VERSION_CONFLICT", "资源版本已变化，请刷新后重试", 409),
    IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT", "幂等键已用于不同请求", 409),
    SOURCE_MAPPING_REQUIRED("SOURCE_MAPPING_REQUIRED", "数据来源尚未配置语义映射", 422),
    SAMPLE_IDENTITY_CONFLICT("SAMPLE_IDENTITY_CONFLICT", "样本身份存在冲突，需人工审查", 422),
    TARGET_SEMANTIC_MISMATCH("TARGET_SEMANTIC_MISMATCH", "目标值语义与当前定义不匹配", 422),
    MISSING_REQUIRED_X("MISSING_REQUIRED_X", "缺少模型要求的输入字段", 422),
    FORMULA_BASIS_UNRESOLVED("FORMULA_BASIS_UNRESOLVED", "配方比例基准无法确定", 422),
    UNKNOWN_MATERIAL("UNKNOWN_MATERIAL", "配方包含未知材料", 422),
    MATERIAL_NOT_IN_MODEL("MATERIAL_NOT_IN_MODEL", "材料不在模型字典中", 422),
    OUT_OF_DOMAIN("OUT_OF_DOMAIN", "输入超出模型适用域", 422),
    TRAINING_POLICY_NOT_APPROVED("TRAINING_POLICY_NOT_APPROVED", "训练策略尚未批准", 422),
    INSUFFICIENT_DATA("INSUFFICIENT_DATA", "符合资格的训练样本不足", 422),
    REPLICATE_POLICY_REQUIRED("REPLICATE_POLICY_REQUIRED", "重复测量处理方式尚未配置", 422),
    TRAINING_ALREADY_RUNNING("TRAINING_ALREADY_RUNNING", "该目标已有训练任务执行中", 409),
    TRAINING_TIMEOUT("TRAINING_TIMEOUT", "模型训练超时", 504),
    STALE_TRAINING_ATTEMPT("STALE_TRAINING_ATTEMPT", "训练任务租约已经过期", 409),
    MODEL_NOT_COMPARABLE("MODEL_NOT_COMPARABLE", "候选模型缺少同口径比较证据", 422),
    MODEL_NOT_PRODUCTION_ELIGIBLE("MODEL_NOT_PRODUCTION_ELIGIBLE", "该模型不具备生产启用资格", 422),
    ELIGIBILITY_CONFIG_NOT_READY("ELIGIBILITY_CONFIG_NOT_READY", "资格评估所需配置尚未发布或冻结", 422),
    ELIGIBILITY_NOT_EVALUATED("ELIGIBILITY_NOT_EVALUATED", "资格尚未评估", 409),
    REVIEW_DECISION_NOT_ALLOWED("REVIEW_DECISION_NOT_ALLOWED", "当前审查对象不允许该决定", 422),
    NO_ACTIVE_MODEL("NO_ACTIVE_MODEL", "目标尚无可用的正式模型", 422),
    MODEL_VERSION_CHANGED("MODEL_VERSION_CHANGED", "请求绑定的模型版本已变化", 409),
    QUALITY_POLICY_NOT_READY("QUALITY_POLICY_NOT_READY", "质量策略尚未发布", 422),
    DOMAIN_POLICY_NOT_READY("DOMAIN_POLICY_NOT_READY", "适用域策略尚未发布或未完整配置", 422),
    GOAL_OPERATOR_NOT_SUPPORTED("GOAL_OPERATOR_NOT_SUPPORTED", "当前目标不支持该运算", 422),
    GOAL_VALUE_INVALID("GOAL_VALUE_INVALID", "目标约束值无效", 422),
    MINIMUM_PROBABILITY_REQUIRED("MINIMUM_PROBABILITY_REQUIRED", "离散目标必须填写最低概率", 422),
    MATERIAL_SPACE_CONFLICT("MATERIAL_SPACE_CONFLICT", "材料搜索空间无法同时满足所选目标", 422),
    INPUT_SPACE_CONFLICT("INPUT_SPACE_CONFLICT", "输入条件空间无法同时满足所选目标", 422),
    FIXED_CONSTRAINT_CONFLICT("FIXED_CONSTRAINT_CONFLICT", "固定条件与搜索约束冲突", 422),
    MODEL_ARTIFACT_INVALID("MODEL_ARTIFACT_INVALID", "模型制品无效或校验失败", 503),
    COMPUTE_UNAVAILABLE("COMPUTE_UNAVAILABLE", "计算服务暂不可用", 503),
    SEARCH_TIMEOUT("SEARCH_TIMEOUT", "配方搜索超时", 504),
    STALE_RESEARCH_RESULT("STALE_RESEARCH_RESULT", "配方搜索结果已过期", 409),
    BASELINE_REQUIRED("BASELINE_REQUIRED", "必须选择一个优化基线", 422),
    BASELINE_NOT_CURRENT("BASELINE_NOT_CURRENT", "所选基线已不是当前版本", 409),
    BASELINE_VERSION_CHANGED("BASELINE_VERSION_CHANGED", "基线版本已变化，请重新确认", 409),
    BASELINE_DATA_INCOMPLETE("BASELINE_DATA_INCOMPLETE", "基线缺少完整配方或实验前条件", 422),
    BASELINE_OUT_OF_DOMAIN("BASELINE_OUT_OF_DOMAIN", "基线超出所选目标模型适用域", 422),
    NO_ADJUSTABLE_INPUT("NO_ADJUSTABLE_INPUT", "至少需要一个允许调整的配方或实验前输入", 422),
    OPTIMIZATION_SPACE_CONFLICT("OPTIMIZATION_SPACE_CONFLICT", "实验优化的可变空间无法满足约束", 422),
    TARGET_TOTAL_CONFLICT("TARGET_TOTAL_CONFLICT", "目标配方总量与固定材料约束冲突", 422),
    STRATEGY_NOT_FEASIBLE("STRATEGY_NOT_FEASIBLE", "当前约束下无法生成所需实验策略", 422),
    DRAFT_CREATION_CONFLICT("DRAFT_CREATION_CONFLICT", "实验草稿创建条件已变化", 409),
    FEEDBACK_OBSERVATION_MISSING("FEEDBACK_OBSERVATION_MISSING", "实验完成版本缺少对应实测结果", 422),
    FEEDBACK_SEMANTIC_MISMATCH("FEEDBACK_SEMANTIC_MISMATCH", "实测结果语义与预测目标不匹配", 422),
    FEEDBACK_UNIT_INCOMPATIBLE("FEEDBACK_UNIT_INCOMPATIBLE", "实测结果单位与预测目标不兼容", 422),
    INFEASIBLE_CONSTRAINTS("INFEASIBLE_CONSTRAINTS", "多个目标或限制条件无法同时满足", 422),
    NO_FEASIBLE_CANDIDATE("NO_FEASIBLE_CANDIDATE", "未找到满足条件的候选方案", 422),
    MODEL_ARTIFACT_UNAVAILABLE("MODEL_ARTIFACT_UNAVAILABLE", "模型制品暂不可用", 503),
    AI_PROVIDER_UNAVAILABLE("AI_PROVIDER_UNAVAILABLE", "AI 服务暂不可用", 503),
    SNAPSHOT_PERSIST_FAILED("SNAPSHOT_PERSIST_FAILED", "编辑器快照未能安全持久化", 500),
    INTERNAL_ERROR("SYS_INTERNAL_ERROR", "系统内部错误", 500);

    private final String code;
    private final String defaultMessage;
    private final int httpStatus;

    ApiErrorCode(String code, String defaultMessage, int httpStatus) {
        this.code = code;
        this.defaultMessage = defaultMessage;
        this.httpStatus = httpStatus;
    }

    public String code() {
        return code;
    }

    public String defaultMessage() {
        return defaultMessage;
    }

    public int httpStatus() {
        return httpStatus;
    }
}
