CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS mdm;
CREATE SCHEMA IF NOT EXISTS tpl;
CREATE SCHEMA IF NOT EXISTS rnd;
CREATE SCHEMA IF NOT EXISTS quality;
CREATE SCHEMA IF NOT EXISTS spc;
CREATE SCHEMA IF NOT EXISTS mfg;
CREATE SCHEMA IF NOT EXISTS kb;
CREATE SCHEMA IF NOT EXISTS ai;
CREATE SCHEMA IF NOT EXISTS ops;

COMMENT ON SCHEMA core IS '统一业务对象注册与跨域引用';
COMMENT ON SCHEMA iam IS '组织、用户、角色、权限与数据范围';
COMMENT ON SCHEMA mdm IS '主数据、别名、重复识别与合并';
COMMENT ON SCHEMA tpl IS '统一模板中心与运行时动态值';
COMMENT ON SCHEMA rnd IS '需求、项目、实验、配方与样品';
COMMENT ON SCHEMA quality IS '标准、检验、判定与报告';
COMMENT ON SCHEMA spc IS '图谱、曲线、处理、特征与比对';
COMMENT ON SCHEMA mfg IS '生产、批次、库存与追溯';
COMMENT ON SCHEMA kb IS '知识版本、ACL、全文与向量';
COMMENT ON SCHEMA ai IS '数据集、分析、模型、预测与优化';
COMMENT ON SCHEMA ops IS '文件、导入、任务、审计与Outbox';

