package com.jsd.aird.mfg.inventory.application;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.jsd.aird.mfg.inventory.domain.InventoryModels.*;
import com.jsd.aird.mfg.inventory.application.port.InventoryRepository;
import com.jsd.aird.ops.application.port.AuditLogFacade;
import com.jsd.aird.shared.error.ApiErrorCode;
import com.jsd.aird.shared.error.ApiException;
import com.jsd.aird.shared.security.ActorContext;
import com.jsd.aird.shared.security.Actor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

@Service
public class InventoryService {
    private final InventoryRepository repository; private final AuditLogFacade audit; private final ObjectMapper mapper;
    public InventoryService(InventoryRepository repository, AuditLogFacade audit, ObjectMapper mapper){this.repository=repository;this.audit=audit;this.mapper=mapper;}
    public BalancePage balances(String keyword,Scope scope,AlertStatus alert,int page,int size){return repository.balances(actor().organizationId(),keyword,scope,alert,Math.max(page,1),Math.min(Math.max(size,1),100));}
    public java.util.List<ProductOption> productOptions(Scope scope,String keyword){return repository.productOptions(actor().organizationId(),scope,keyword);}
    @Transactional public ProductOption createProduct(ProductInput input){if(input==null||input.scope()==null)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"库存域不能为空");var a=actor();var name=required(input.name(),"产品名称");var product=repository.createProduct(a.organizationId(),name,input.scope(),a.userId());audit.append(a.organizationId(),a.userId(),"INVENTORY_PRODUCT_CREATED","INVENTORY_PRODUCT",product.id(),mapper.valueToTree(input));return product;}
    public Balance balance(UUID product,Scope scope){return repository.balance(actor().organizationId(),product,scope).orElseThrow(()->new ApiException(ApiErrorCode.NOT_FOUND,"库存产品不存在"));}
    @Transactional public Balance updatePolicy(UUID product,Scope scope,PolicyInput input){var a=actor();if(!repository.productExists(a.organizationId(),product,scope))throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"该库存域中产品不存在或已停用");if(input.lowStockKg()==null||input.lowStockKg().signum()<0||input.packageKg()!=null&&input.packageKg().signum()<=0)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"包装规格必须大于 0，预警阈值不能为负数");repository.upsertPolicy(a.organizationId(),product,scope,input.packageKg(),input.lowStockKg(),a.userId());audit.append(a.organizationId(),a.userId(),"INVENTORY_POLICY_UPDATED","INVENTORY_POLICY",product,mapper.valueToTree(input));return balance(product,scope);}
    public Page<Transaction> transactions(Scope scope,String keyword,String direction,String reason,int page,int size){return repository.transactions(actor().organizationId(),scope,keyword,direction,reason,Math.max(page,1),Math.min(Math.max(size,1),100));}
    public Transaction transaction(UUID id){return repository.findTransaction(actor().organizationId(),id).orElseThrow(()->new ApiException(ApiErrorCode.NOT_FOUND,"库存流水不存在"));}

    @Transactional
    public Transaction move(Movement command,String idempotencyKey){
        var a=actor(); var existing=repository.findByIdempotency(a.organizationId(),idempotencyKey); if(existing.isPresent())return existing.get();
        validate(command); var before=repository.lockBalance(a.organizationId(),command.productId(),command.scope(),a.userId());
        var after=command.direction()==Direction.INBOUND?before.add(command.quantityKg()):before.subtract(command.quantityKg());
        if(after.signum()<0)throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"库存不足，当前可用 "+before.stripTrailingZeros().toPlainString()+" KG",java.util.Map.of("availableKg",before));
        var id=UUID.randomUUID();var tx=new Transaction(id,command.productId(),null,null,null,command.scope(),command.direction(),required(command.reason(),"业务原因"),command.quantityKg(),before,after,command.businessDate()==null?LocalDate.now():command.businessDate(),required(command.documentNo(),"业务单号"),command.businessType()==null?"MANUAL":command.businessType(),command.businessId(),null,command.note(),a.userId(),null,null,false);
        try{repository.insertTransaction(a.organizationId(),tx,idempotencyKey);repository.updateBalance(a.organizationId(),command.productId(),command.scope(),after);}catch(DataIntegrityViolationException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"业务单号或幂等键已存在",e);}
        audit.append(a.organizationId(),a.userId(),"INVENTORY_MOVED","INVENTORY_TRANSACTION",id,mapper.valueToTree(command)); return repository.findTransaction(a.organizationId(),id).orElseThrow();
    }

    @Transactional
    public Transaction reverse(UUID id,String note,String idempotencyKey){var a=actor();var original=transaction(id);if(original.reversed()||original.reversalOf()!=null)throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"该流水不可重复冲销");var reverseDirection=original.direction()==Direction.INBOUND?Direction.OUTBOUND:Direction.INBOUND;var movement=new Movement(original.productId(),original.scope(),reverseDirection,"REVERSAL",original.quantityKg(),LocalDate.now(),"REV-"+original.documentNo(),"REVERSAL",original.id(),note);var before=repository.lockBalance(a.organizationId(),original.productId(),original.scope(),a.userId());var after=reverseDirection==Direction.INBOUND?before.add(original.quantityKg()):before.subtract(original.quantityKg());if(after.signum()<0)throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"当前库存不足，无法冲销该入库流水");var rid=UUID.randomUUID();var tx=new Transaction(rid,original.productId(),null,null,null,original.scope(),reverseDirection,"REVERSAL",original.quantityKg(),before,after,LocalDate.now(),movement.documentNo(),"REVERSAL",original.id(),original.id(),note,a.userId(),null,null,false);try{repository.insertTransaction(a.organizationId(),tx,idempotencyKey);repository.updateBalance(a.organizationId(),original.productId(),original.scope(),after);}catch(DataIntegrityViolationException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"该流水已冲销",e);}audit.append(a.organizationId(),a.userId(),"INVENTORY_REVERSED","INVENTORY_TRANSACTION",rid,mapper.valueToTree(java.util.Map.of("reversalOf",id)));return repository.findTransaction(a.organizationId(),rid).orElseThrow();}

    @Transactional public Transaction updateTransaction(UUID id,TransactionUpdateInput input){var a=actor();var original=transaction(id);if(original.reversed()||original.reversalOf()!=null)throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"已冲销或冲销流水不可编辑");if(input==null||input.businessDate()==null)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"业务日期不能为空");var documentNo=required(input.documentNo(),"业务单号");var reason=required(input.reason(),"业务原因");try{if(repository.updateTransaction(a.organizationId(),id,input.businessDate(),documentNo,reason,input.note())==0)throw new ApiException(ApiErrorCode.NOT_FOUND,"库存流水不存在");}catch(DataIntegrityViolationException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"业务单号或业务原因已存在",e);}audit.append(a.organizationId(),a.userId(),"INVENTORY_TRANSACTION_UPDATED","INVENTORY_TRANSACTION",id,mapper.valueToTree(input));return transaction(id);}

    @Transactional public Sample createSample(SampleInput c,String key){var a=actor();var prior=repository.findByIdempotency(a.organizationId(),key);if(prior.isPresent())return repository.sampleByTransaction(a.organizationId(),prior.get().id()).orElseThrow(()->new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"幂等请求尚未完成"));var customerName=customerName(c.customerId());var id=UUID.randomUUID();var tx=move(new Movement(c.productId(),Scope.RND,Direction.OUTBOUND,"SAMPLE_DISPATCH",c.quantityKg(),c.businessDate(),c.dispatchNo(),"SAMPLE",id,c.customerRequirement()),key);var x=new Sample(id,c.dispatchNo(),c.businessDate(),c.productId(),tx.productName(),c.quantityKg(),c.customerId(),customerName,required(c.recipientName(),"收件人"),c.sampleAddress(),c.courierCompany(),c.trackingNo(),c.clientContact(),c.customerRequirement(),c.customerFeedback(),tx.id(),null,null);repository.insertSample(a.organizationId(),x,a.userId());return repository.sampleByTransaction(a.organizationId(),tx.id()).orElseThrow();}
    @Transactional public Shipment createShipment(ShipmentInput c,String key){var a=actor();var prior=repository.findByIdempotency(a.organizationId(),key);if(prior.isPresent())return repository.shipmentByTransaction(a.organizationId(),prior.get().id()).orElseThrow(()->new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"幂等请求尚未完成"));var customerName=customerName(c.customerId());var id=UUID.randomUUID();var tx=move(new Movement(c.productId(),Scope.PRODUCTION,Direction.OUTBOUND,"SHIPMENT",c.quantityKg(),c.businessDate(),c.shipmentNo(),"SHIPMENT",id,c.note()),key);var x=new Shipment(id,c.shipmentNo(),c.businessDate(),c.productId(),tx.productName(),c.quantityKg(),c.customerId(),customerName,c.note(),tx.id(),null,null);repository.insertShipment(a.organizationId(),x,a.userId());return repository.shipmentByTransaction(a.organizationId(),tx.id()).orElseThrow();}
    @Transactional public Sample updateSample(UUID id,SampleUpdateInput input){var a=actor();if(input==null||input.businessDate()==null)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"业务日期不能为空");var existing=repository.findSample(a.organizationId(),id).orElseThrow(()->new ApiException(ApiErrorCode.NOT_FOUND,"发样记录不存在"));var dispatchNo=required(input.dispatchNo(),"发样单号");var recipientName=required(input.recipientName(),"收件人");var customerName=customerName(input.customerId());try{if(repository.updateSample(a.organizationId(),id,input.businessDate(),dispatchNo,input.customerId(),customerName,recipientName,input.sampleAddress(),input.courierCompany(),input.trackingNo(),input.clientContact(),input.customerRequirement(),input.customerFeedback())==0)throw new ApiException(ApiErrorCode.NOT_FOUND,"发样记录不存在");}catch(DataIntegrityViolationException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"发样单号已存在",e);}audit.append(a.organizationId(),a.userId(),"INVENTORY_SAMPLE_UPDATED","INVENTORY_SAMPLE_DISPATCH",id,mapper.valueToTree(input));return repository.findSample(a.organizationId(),existing.id()).orElseThrow();}
    @Transactional public Shipment updateShipment(UUID id,ShipmentUpdateInput input){var a=actor();if(input==null||input.businessDate()==null)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"业务日期不能为空");var existing=repository.findShipment(a.organizationId(),id).orElseThrow(()->new ApiException(ApiErrorCode.NOT_FOUND,"出货记录不存在"));var shipmentNo=required(input.shipmentNo(),"出货单号");var customerName=customerName(input.customerId());try{if(repository.updateShipment(a.organizationId(),id,input.businessDate(),shipmentNo,input.customerId(),customerName,input.note())==0)throw new ApiException(ApiErrorCode.NOT_FOUND,"出货记录不存在");}catch(DataIntegrityViolationException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"出货单号已存在",e);}audit.append(a.organizationId(),a.userId(),"INVENTORY_SHIPMENT_UPDATED","INVENTORY_SHIPMENT",id,mapper.valueToTree(input));return repository.findShipment(a.organizationId(),existing.id()).orElseThrow();}
    public Page<Sample> samples(int page,int size){return repository.samples(actor().organizationId(),Math.max(page,1),Math.min(Math.max(size,1),100));} public Page<Shipment> shipments(int page,int size){return repository.shipments(actor().organizationId(),Math.max(page,1),Math.min(Math.max(size,1),100));}
    private void validate(Movement c){if(c==null||c.productId()==null||c.scope()==null||c.direction()==null)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"产品、库存域和方向不能为空");if(c.quantityKg()==null||c.quantityKg().signum()<=0)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"数量必须大于 0");if(!repository.productExists(actor().organizationId(),c.productId(),c.scope()))throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"该库存域中产品不存在或已停用");required(c.reason(),"业务原因");required(c.documentNo(),"业务单号");}
    private static String required(String x,String label){if(x==null||x.isBlank())throw new ApiException(ApiErrorCode.VALIDATION_ERROR,label+"不能为空");return x.trim();}
    private static Actor actor(){return ActorContext.required();}
    private String customerName(UUID customerId){if(customerId==null)throw new ApiException(ApiErrorCode.VALIDATION_ERROR,"客户不能为空");return repository.activeCustomerName(customerId).orElseThrow(()->new ApiException(ApiErrorCode.VALIDATION_ERROR,"客户不存在或已停用"));}
    public record SampleInput(String dispatchNo,LocalDate businessDate,UUID productId,BigDecimal quantityKg,UUID customerId,String recipientName,String sampleAddress,String courierCompany,String trackingNo,String clientContact,String customerRequirement,String customerFeedback){}
    public record ShipmentInput(String shipmentNo,LocalDate businessDate,UUID productId,BigDecimal quantityKg,UUID customerId,String note){}
    public record TransactionUpdateInput(LocalDate businessDate,String documentNo,String reason,String note){}
    public record SampleUpdateInput(String dispatchNo,LocalDate businessDate,UUID customerId,String recipientName,String sampleAddress,String courierCompany,String trackingNo,String clientContact,String customerRequirement,String customerFeedback){}
    public record ShipmentUpdateInput(String shipmentNo,LocalDate businessDate,UUID customerId,String note){}
    public record PolicyInput(BigDecimal packageKg,BigDecimal lowStockKg){}
    public record ProductInput(String name,Scope scope){}
}
