"""Build an isolated V2 bundle whose frozen input scheme has no composition field.

This fixture exists only for the R10 browser acceptance database.  It proves
that a target which does not declare formula composition can be scored without
requiring a formula payload.
"""
from __future__ import annotations

import hashlib
import io
import json
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

from jsd_aird_ai.api import create_app
from jsd_aird_ai.service_v2 import FormulaModelV2Service
from jsd_aird_ai.settings import Settings


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "tmp" / "r10-noformula"


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write_ref(path: Path, data: bytes) -> dict[str, str]:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return {"url": path.resolve().as_uri(), "sha256": sha(data)}


def parquet(rows: list[dict]) -> bytes:
    target = io.BytesIO()
    pq.write_table(pa.Table.from_pylist(rows), target)
    return target.getvalue()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows: list[dict] = []
    sources: list[dict] = []
    for index in range(36):
        rows.append({
            "row_id": f"noformula-{index}",
            # The raw formula is retained in the snapshot, but it is not part
            # of the frozen input scheme and therefore must not be encoded.
            "formula_json": json.dumps({"recordedTotal": 98.8 if index == 0 else 100.0}),
            "inputs_json": json.dumps({"temperature": 20 + index % 5}),
            "target_numeric": 40.0 + index * 0.8,
            "target_label": None,
        })
        sources.append({"row_id": f"noformula-{index}", "formula_lineage": f"lineage-{index // 2}", "source_context": f"source-{index // 3}", "sample_id": f"sample-{index}"})
    snapshot_hash = "a" * 64
    rows_ref = write_ref(OUT / "rows.parquet", parquet(rows))
    source_ref = write_ref(OUT / "source.parquet", parquet(sources))
    manifest_ref = write_ref(OUT / "manifest.json", json.dumps({"snapshotHash": snapshot_hash}).encode())
    scheme = {
        "id": "noformula-scheme-v1", "version": 1, "sha256": "b" * 64,
        "targetVersionId": "noformula-target-v1", "fields": [{
            "fieldVersionId": "temperature-v1", "code": "temperature",
            "valueType": "NUMBER", "required": True,
            "acquisitionTiming": "PRE_EXPERIMENT", "encoding": {},
        }],
    }
    request = {
        "contractVersion": "formula-model.v2", "requestId": "r10-noformula-train", "seed": 37,
        "snapshot": {"id": "noformula-snapshot", "version": 1, "sha256": snapshot_hash,
                      "manifest": manifest_ref, "rows": rows_ref, "sourceMap": source_ref},
        "context": {
            "targetDefinition": {"id": "90000000-0000-0000-0000-000000000002", "version": 1, "sha256": "c" * 64,
                                  "code": "R10_NO_FORMULA_GLOSS", "valueType": "CONTINUOUS", "unit": "GU", "classes": [], "observationSemantics": {}},
            "inputScheme": scheme,
            "materialDictionary": {"id": "05060000-0000-0000-0000-000000000020", "version": 1, "sha256": "9ec2ae3b255cbfffd974b98cff5ba85eca5933763f3698f1dbafe2d0afd986fb", "materials": [
                {"materialId": "05060000-0000-0000-0000-000000000031", "code": "R0506-RESIN", "role": "RESIN", "encoderIndex": 0},
                {"materialId": "05060000-0000-0000-0000-000000000032", "code": "R0506-ADDITIVE", "role": "ADDITIVE", "encoderIndex": 1}]},
            "preprocessing": {"id": "preprocessing-v1", "version": 1, "sha256": "0" * 64, "config": {}},
            "trainingPolicy": {"id": "noformula-policy", "version": 1, "sha256": "f" * 64,
                                "config": {"candidateAlgorithms": ["RANDOM_FOREST"], "replicateHandling": "KEEP_GROUPED"}},
        },
    }
    service = FormulaModelV2Service(Settings(allow_file_urls=True, temporary_root=OUT))
    app = create_app(Settings(allow_file_urls=True, temporary_root=OUT))
    # Use the service's public V2 path through its ASGI app so the artifact is
    # generated by the same contract used by the running Python service.
    from fastapi.testclient import TestClient
    client = TestClient(app)
    folds = client.post("/internal/v2/snapshots/validation-folds", json=request | {"foldCount": 4, "groupFields": ["formula_lineage", "source_context"]})
    if folds.status_code != 200:
        raise RuntimeError(f"fold generation failed: {folds.status_code} {folds.text}")
    folds_ref = write_ref(OUT / "folds.json", json.dumps({"assignments": folds.json()["assignments"]}).encode())
    output = OUT / "model.zip"
    trained = client.post("/internal/v2/models/train", json=request | {"jobId": "r10-noformula-job", "validationFolds": folds_ref, "output": output.resolve().as_uri()})
    trained.raise_for_status()
    result = trained.json()
    (OUT / "training-result.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    with __import__("zipfile").ZipFile(output) as archive:
        model_card = json.loads(archive.read("model-card.json").decode("utf-8"))
    print(json.dumps({"bundle": str(output.resolve()), "sha256": sha(output.read_bytes()), "applicability": result["applicabilityDomain"], "modelCard": model_card}, ensure_ascii=False))


if __name__ == "__main__":
    main()
