import { FileUnknownOutlined } from '@ant-design/icons';
import { useVirtualizer } from '@tanstack/react-virtual';
import { Alert, Empty, Spin, Typography } from 'antd';
import type { PDFDocumentLoadingTask, PDFDocumentProxy, PDFPageProxy } from 'pdfjs-dist';
import { useEffect, useRef, useState } from 'react';
import type * as XLSX from 'xlsx';

import type { SourceAnchor, SourceNode } from '@/services/knowledge';

export interface OriginalDocumentViewerProps { fileName: string; contentType: string; load: () => Promise<Blob>; sourceNodes: SourceNode[]; selectedSourceNodeKey?: string; onSourceSelect?: (sourceNodeKey: string) => void }

export function OriginalDocumentViewer(props: OriginalDocumentViewerProps) {
  const [blob, setBlob] = useState<Blob>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  const selected = props.sourceNodes.find((item) => item.sourceNodeKey === props.selectedSourceNodeKey);
  useEffect(() => { let active = true; setLoading(true); setError(undefined); props.load().then((value) => { if (active) setBlob(value); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : '原文件加载失败'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [props.fileName, props.load]);
  if (loading) return <div className="knowledge-viewer-state"><Spin tip="正在加载原文件" /></div>;
  if (error || !blob) return <div className="knowledge-viewer-state"><Alert type="error" showIcon message={error || '原文件不可读取'} /></div>;
  const name = props.fileName.toLowerCase(); const type = props.contentType.toLowerCase();
  if (type === 'application/pdf' || name.endsWith('.pdf')) return <PdfViewer blob={blob} selected={selected?.sourceAnchor} sourceNodes={props.sourceNodes} onSourceSelect={props.onSourceSelect} />;
  if (type.startsWith('image/') || /\.(png|jpe?g|gif|webp|bmp|tiff?)$/.test(name)) return <ImageViewer blob={blob} selected={selected?.sourceAnchor} sourceNodes={props.sourceNodes} onSourceSelect={props.onSourceSelect} />;
  if (type.startsWith('audio/') || /\.(mp3|wav|m4a|aac|flac|ogg|opus)$/.test(name)) return <AudioViewer blob={blob} selected={selected?.sourceAnchor} sourceNodes={props.sourceNodes} onSourceSelect={props.onSourceSelect} />;
  if (name.endsWith('.docx')) return <DocxViewer blob={blob} selected={selected?.sourceAnchor} sourceNodes={props.sourceNodes} onSourceSelect={props.onSourceSelect} />;
  if (/\.(xlsx|xls|csv)$/.test(name)) return <WorkbookViewer blob={blob} selected={selected?.sourceAnchor} sourceNodes={props.sourceNodes} onSourceSelect={props.onSourceSelect} />;
  if (type.startsWith('text/') || /\.(txt|md)$/.test(name)) return <TextViewer blob={blob} />;
  return <div className="knowledge-viewer-state"><Empty image={<FileUnknownOutlined style={{ fontSize: 36 }} />} description="此格式首期仅提供解析文本对照，请下载原文件查看完整格式" /></div>;
}

function PdfViewer({ blob, selected, sourceNodes, onSourceSelect }: { blob: Blob; selected?: SourceAnchor; sourceNodes: SourceNode[]; onSourceSelect?: (key: string) => void }) {
  const [pdf, setPdf] = useState<PDFDocumentProxy>();
  useEffect(() => { let task: PDFDocumentLoadingTask | undefined; void Promise.all([blob.arrayBuffer(), import('pdfjs-dist')]).then(([data, pdfjs]) => { pdfjs.GlobalWorkerOptions.workerSrc = new URL('pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url).toString(); task = pdfjs.getDocument({ data }); return task.promise; }).then(setPdf); return () => { void task?.destroy(); }; }, [blob]);
  useEffect(() => { if (selected?.page) document.getElementById(`knowledge-pdf-page-${selected.page}`)?.scrollIntoView({ block: 'center', behavior: 'smooth' }); }, [selected]);
  if (!pdf) return <div className="knowledge-viewer-state"><Spin /></div>;
  return <div className="knowledge-pdf-pages">{Array.from({ length: pdf.numPages }, (_, index) => <PdfPage key={index + 1} pdf={pdf} pageNo={index + 1} highlight={selected?.page === index + 1 ? selected : undefined} onClick={(x, y) => { const pageNo = index + 1; const node = sourceNodes.find((item) => item.sourceAnchor.page === pageNo && anchorContainsPoint(item.sourceAnchor, x, y)) || sourceNodes.find((item) => item.sourceAnchor.page === pageNo); if (node) onSourceSelect?.(node.sourceNodeKey); }} />)}</div>;
}

function PdfPage({ pdf, pageNo, highlight, onClick }: { pdf: PDFDocumentProxy; pageNo: number; highlight?: SourceAnchor; onClick: (x: number, y: number) => void }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [page, setPage] = useState<PDFPageProxy>(); const [size, setSize] = useState({ width: 0, height: 0 });
  useEffect(() => { void pdf.getPage(pageNo).then(setPage); }, [pageNo, pdf]);
  useEffect(() => { if (!page || !canvas.current) return; const viewport = page.getViewport({ scale: 1.25 }); const ratio = window.devicePixelRatio || 1; const context = canvas.current.getContext('2d'); if (!context) return; canvas.current.width = viewport.width * ratio; canvas.current.height = viewport.height * ratio; canvas.current.style.width = `${viewport.width}px`; canvas.current.style.height = `${viewport.height}px`; setSize({ width: viewport.width, height: viewport.height }); void page.render({ canvas: canvas.current, canvasContext: context, viewport, transform: ratio === 1 ? undefined : [ratio, 0, 0, ratio, 0, 0] }).promise; }, [page]);
  return <figure id={`knowledge-pdf-page-${pageNo}`} className={`knowledge-pdf-page${highlight ? ' is-selected' : ''}`} onClick={(event) => { const target = canvas.current; if (!target) return; const rect = target.getBoundingClientRect(); onClick((event.clientX - rect.left) / Math.max(rect.width, 1), (event.clientY - rect.top) / Math.max(rect.height, 1)); }}><canvas ref={canvas} />{highlight?.kind === 'page_region' && <AnchorOverlay anchor={highlight} width={size.width} height={size.height} />}<figcaption>第 {pageNo} 页</figcaption></figure>;
}

function AnchorOverlay({ anchor, width, height }: { anchor: SourceAnchor; width: number; height: number }) { const values = (anchor.polygon || []).flat(); if (values.length < 4) return null; const xs = values.filter((_, index) => index % 2 === 0); const ys = values.filter((_, index) => index % 2 === 1); const left = Math.min(...xs) * width; const top = Math.min(...ys) * height; return <span className="knowledge-source-highlight" style={{ left, top, width: (Math.max(...xs) - Math.min(...xs)) * width, height: (Math.max(...ys) - Math.min(...ys)) * height }} />; }

function ImageViewer({ blob, selected, sourceNodes, onSourceSelect }: { blob: Blob; selected?: SourceAnchor; sourceNodes: SourceNode[]; onSourceSelect?: (key: string) => void }) { const [url, setUrl] = useState(''); const [size, setSize] = useState({ width: 0, height: 0 }); useEffect(() => { const value = URL.createObjectURL(blob); setUrl(value); return () => URL.revokeObjectURL(value); }, [blob]); return <div className="knowledge-image-stage"><div className="knowledge-image-frame" onClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left) / Math.max(rect.width, 1); const y = (event.clientY - rect.top) / Math.max(rect.height, 1); const source = sourceNodes.find((node) => anchorContainsPoint(node.sourceAnchor, x, y)) || sourceNodes[0]; if (source) onSourceSelect?.(source.sourceNodeKey); }}><img src={url} alt="原图" onLoad={(event) => setSize({ width: event.currentTarget.clientWidth, height: event.currentTarget.clientHeight })} />{selected?.kind === 'page_region' && <AnchorOverlay anchor={selected} width={size.width} height={size.height} />}</div></div>; }

function AudioViewer({ blob, selected, sourceNodes, onSourceSelect }: { blob: Blob; selected?: SourceAnchor; sourceNodes: SourceNode[]; onSourceSelect?: (key: string) => void }) { const [url, setUrl] = useState(''); const audio = useRef<HTMLAudioElement>(null); useEffect(() => { const value = URL.createObjectURL(blob); setUrl(value); return () => URL.revokeObjectURL(value); }, [blob]); useEffect(() => { if (audio.current && selected?.startMs !== undefined) { audio.current.currentTime = selected.startMs / 1000; } }, [selected]); return <div className="knowledge-audio-viewer"><Typography.Title level={4}>原始音频</Typography.Title><audio ref={audio} src={url} controls onSeeked={(event) => { const milliseconds = event.currentTarget.currentTime * 1000; const source = sourceNodes.find((node) => node.sourceAnchor.kind === 'time_range' && (node.sourceAnchor.startMs || 0) <= milliseconds && (node.sourceAnchor.endMs ?? Number.MAX_SAFE_INTEGER) >= milliseconds); if (source) onSourceSelect?.(source.sourceNodeKey); }} /><Typography.Text type="secondary">选择右侧转写段落可定位到对应时间。</Typography.Text></div>; }

function DocxViewer({ blob, selected, sourceNodes, onSourceSelect }: { blob: Blob; selected?: SourceAnchor; sourceNodes: SourceNode[]; onSourceSelect?: (key: string) => void }) { const host = useRef<HTMLDivElement>(null); useEffect(() => { if (host.current) { host.current.innerHTML = ''; const target = host.current; void import('docx-preview').then(({ renderAsync }) => renderAsync(blob, target, target, { breakPages: true, renderHeaders: true, renderFooters: true, renderFootnotes: true, renderEndnotes: true, useBase64URL: true })); } }, [blob]); useEffect(() => { if (!host.current || !selected?.paragraphId) return; const index = Number(selected.paragraphId.replace(/\D/g, '')); host.current.querySelectorAll('p')[index]?.scrollIntoView({ block: 'center', behavior: 'smooth' }); }, [selected]); return <div className="knowledge-docx-viewer" ref={host} onClick={(event) => { const paragraph = (event.target as HTMLElement).closest('p'); if (!paragraph || !host.current) return; const index = [...host.current.querySelectorAll('p')].indexOf(paragraph); const node = sourceNodes.find((item) => item.sourceAnchor.paragraphId === `p-${index}`); if (node) onSourceSelect?.(node.sourceNodeKey); }} />; }

type XlsxModule = typeof XLSX;

function WorkbookViewer({ blob, selected, sourceNodes, onSourceSelect }: { blob: Blob; selected?: SourceAnchor; sourceNodes: SourceNode[]; onSourceSelect?: (key: string) => void }) { const [xlsx, setXlsx] = useState<XlsxModule>(); const [workbook, setWorkbook] = useState<XLSX.WorkBook>(); const [sheetName, setSheetName] = useState(''); useEffect(() => { void Promise.all([blob.arrayBuffer(), import('xlsx')]).then(([data, module]) => { const book = module.read(data, { type: 'array' }); setXlsx(module); setWorkbook(book); setSheetName(selected?.sheetName && book.SheetNames.includes(selected.sheetName) ? selected.sheetName : book.SheetNames[0] || ''); }); }, [blob]); useEffect(() => { if (selected?.sheetName) setSheetName(selected.sheetName); }, [selected]); const sheet = workbook?.Sheets[sheetName]; const range = sheet?.['!ref'] && xlsx ? xlsx.utils.decode_range(sheet['!ref']) : undefined; const rows = range ? range.e.r + 1 : 0; const columns = range ? Math.min(100, range.e.c + 1) : 0; const parent = useRef<HTMLDivElement>(null); const virtual = useVirtualizer({ count: rows, getScrollElement: () => parent.current, estimateSize: () => 32, overscan: 12 }); useEffect(() => { if (selected?.range && xlsx) virtual.scrollToIndex(xlsx.utils.decode_range(selected.range).s.r, { align: 'center' }); }, [selected, virtual, xlsx]); if (!sheet || !xlsx) return <div className="knowledge-viewer-state"><Spin /></div>; return <div className="knowledge-workbook"><div className="knowledge-sheet-tabs">{workbook?.SheetNames.map((name) => <button className={name === sheetName ? 'is-active' : ''} key={name} onClick={() => setSheetName(name)}>{name}</button>)}</div><div className="knowledge-sheet-grid" ref={parent}><div style={{ height: virtual.getTotalSize(), position: 'relative', minWidth: columns * 132 }}>{virtual.getVirtualItems().map((row) => <div className="knowledge-sheet-row" key={row.key} style={{ transform: `translateY(${row.start}px)`, position: 'absolute', top: 0, left: 0, height: row.size }}><span className="knowledge-sheet-row-number">{row.index + 1}</span>{Array.from({ length: columns }, (_, column) => { const address = xlsx.utils.encode_cell({ r: row.index, c: column }); const value = workbookCellText(sheet, address); const active = selected?.sheetName === sheetName && selected.range ? anchorContainsCell(selected.range, row.index, column, xlsx) : false; return <button key={column} className={active ? 'is-selected' : ''} onClick={() => { const source = sourceNodes.find((item) => item.sourceAnchor.sheetName === sheetName && item.sourceAnchor.range && anchorContainsCell(item.sourceAnchor.range, row.index, column, xlsx)); if (source) onSourceSelect?.(source.sourceNodeKey); }}>{value}</button>; })}</div>)}</div></div></div>; }

function workbookCellText(sheet: XLSX.WorkSheet, address: string) { const value: unknown = sheet[address]; if (!value || typeof value !== 'object') return ''; const cell = value as Record<string, unknown>; const display = cell.w ?? cell.v; return typeof display === 'string' || typeof display === 'number' || typeof display === 'boolean' ? String(display) : ''; }

function anchorContainsCell(range: string, row: number, column: number, xlsx: XlsxModule) { try { const decoded = xlsx.utils.decode_range(range); return row >= decoded.s.r && row <= decoded.e.r && column >= decoded.s.c && column <= decoded.e.c; } catch { return false; } }

function anchorContainsPoint(anchor: SourceAnchor, x: number, y: number) { if (anchor.kind !== 'page_region') return false; const values = (anchor.polygon || []).flat(); if (values.length < 4) return false; const xs = values.filter((_, index) => index % 2 === 0); const ys = values.filter((_, index) => index % 2 === 1); return x >= Math.min(...xs) && x <= Math.max(...xs) && y >= Math.min(...ys) && y <= Math.max(...ys); }

function TextViewer({ blob }: { blob: Blob }) { const [text, setText] = useState(''); useEffect(() => { void blob.text().then(setText); }, [blob]); return <pre className="knowledge-text-viewer">{text}</pre>; }
