import { useVirtualizer } from '@tanstack/react-virtual';
import { App, Button, Input, Space, Spin, Tag, Typography } from 'antd';
import { useEffect, useMemo, useRef, useState } from 'react';

import { knowledgeApi, type TableWindow } from '@/services/knowledge';

interface VirtualDataTableProps { documentId: string; sourceTableId: string; versionId?: string; reviewRevisionId?: string; publicationId?: string; lockVersion?: number; editable?: boolean; onLockVersionChange?: (value: number) => void }

export function VirtualDataTable(props: VirtualDataTableProps) {
  const { message } = App.useApp(); const host = useRef<HTMLDivElement>(null); const [windowData, setWindowData] = useState<TableWindow>(); const [loading, setLoading] = useState(false);
  const rowVirtual = useVirtualizer({ count: windowData?.rowCount || 1, getScrollElement: () => host.current, estimateSize: () => 34, overscan: 8 });
  const columnVirtual = useVirtualizer({ horizontal: true, count: windowData?.columnCount || 1, getScrollElement: () => host.current, estimateSize: () => 148, overscan: 4 });
  const rows = rowVirtual.getVirtualItems(); const columns = columnVirtual.getVirtualItems();
  const rowOffset = Math.floor((rows[0]?.index || 0) / 200) * 200; const columnOffset = Math.floor((columns[0]?.index || 0) / 100) * 100;
  useEffect(() => { let active = true; setLoading(true); const query = { rowOffset, rowLimit: 200, columnOffset, columnLimit: 100 }; const request = props.publicationId ? knowledgeApi.publishedTable(props.documentId, props.publicationId, props.sourceTableId, query) : props.versionId && props.reviewRevisionId ? knowledgeApi.reviewTable(props.documentId, props.versionId, props.reviewRevisionId, props.sourceTableId, query) : Promise.reject(new Error('表格上下文缺失')); void request.then((value) => { if (active) setWindowData(value); }).catch((reason) => { if (active) void message.error(reason instanceof Error ? reason.message : '工作表加载失败'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [columnOffset, message, props.documentId, props.publicationId, props.reviewRevisionId, props.sourceTableId, props.versionId, rowOffset]);
  const cells = useMemo(() => new Map((windowData?.cells || []).map((cell) => [`${cell.rowNo}:${cell.columnNo}`, cell])), [windowData]);
  const saveCell = async (rowNo: number, columnNo: number, value: string) => { if (!props.editable || !props.versionId || !props.reviewRevisionId || props.lockVersion === undefined) return; try { await knowledgeApi.saveReviewTable(props.documentId, props.versionId, props.reviewRevisionId, props.sourceTableId, { lockVersion: props.lockVersion, patches: [{ rowNo, columnNo, value }], rows: [], rowOffset, rowLimit: 200, columnOffset, columnLimit: 100 }); props.onLockVersionChange?.(props.lockVersion + 1); setWindowData((current) => current ? { ...current, cells: current.cells.map((cell) => cell.rowNo === rowNo && cell.columnNo === columnNo ? { ...cell, value, patched: true } : cell) } : current); } catch (reason) { void message.error(reason instanceof Error ? reason.message : '单元格保存失败'); } };
  const saveRow = async (rowNo: number, excluded: boolean, header: boolean) => { if (!props.editable || !props.versionId || !props.reviewRevisionId || props.lockVersion === undefined) return; try { const result = await knowledgeApi.saveReviewTable(props.documentId, props.versionId, props.reviewRevisionId, props.sourceTableId, { lockVersion: props.lockVersion, patches: [], rows: [{ rowNo, excluded, header }], rowOffset, rowLimit: 200, columnOffset, columnLimit: 100 }); props.onLockVersionChange?.(props.lockVersion + 1); setWindowData(result); } catch (reason) { void message.error(reason instanceof Error ? reason.message : '行状态保存失败'); } };
  if (!windowData) return <div className="knowledge-viewer-state"><Spin /></div>;
  return <section className="knowledge-virtual-table"><header><div><Typography.Text strong>{windowData.sheetName}</Typography.Text><Typography.Text type="secondary"> · {windowData.rowCount.toLocaleString()} 行 × {windowData.columnCount} 列</Typography.Text></div><Tag color="blue">虚拟表格</Tag></header><div className="knowledge-virtual-grid" ref={host}><div style={{ height: rowVirtual.getTotalSize(), width: columnVirtual.getTotalSize() + 72, position: 'relative' }}>{rows.map((row) => <div className={`knowledge-virtual-row${windowData.excludedRows.includes(row.index) ? ' is-excluded' : ''}`} key={row.key} style={{ position: 'absolute', transform: `translateY(${row.start}px)`, height: row.size, width: '100%' }}><div className="knowledge-virtual-row-actions"><span>{row.index + 1}</span>{props.editable && <Space size={0}><Button type="text" size="small" onClick={() => void saveRow(row.index, !windowData.excludedRows.includes(row.index), false)}>{windowData.excludedRows.includes(row.index) ? '恢复' : '排除'}</Button><Button type="text" size="small" onClick={() => void saveRow(row.index, false, true)}>表头</Button></Space>}</div>{columns.map((column) => { const cell = cells.get(`${row.index}:${column.index}`); return <div className={`knowledge-virtual-cell${cell?.patched ? ' is-patched' : ''}`} key={column.key} style={{ position: 'absolute', left: column.start + 72, width: column.size, height: row.size }}>{props.editable ? <Input variant="borderless" defaultValue={cell?.value || ''} onBlur={(event) => { if (event.target.value !== (cell?.value || '')) void saveCell(row.index, column.index, event.target.value); }} /> : <span>{cell?.value || ''}</span>}</div>; })}</div>)}</div>{loading && <Spin className="knowledge-virtual-loading" size="small" />}</div></section>;
}
