package com.jsd.aird.quality.infrastructure;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jsd.aird.quality.application.QualityDataService;
import com.jsd.aird.quality.application.port.QualityDataStore;
import com.jsd.aird.quality.application.port.QualityDataStore.Category;
import com.jsd.aird.quality.application.port.QualityDataStore.RecordView;
import com.jsd.aird.quality.application.port.QualityDataStore.UploadView;
import com.jsd.aird.quality.application.port.QualityDataStore.VersionView;
import com.jsd.aird.shared.api.PageResponse;
import com.jsd.aird.shared.error.ApiErrorCode;
import com.jsd.aird.shared.error.ApiException;
import org.postgresql.util.PGobject;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public class QualityDataRepository implements QualityDataStore {
    private final JdbcTemplate jdbc; private final ObjectMapper mapper;
    public QualityDataRepository(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    public List<Category> categories(UUID org,String type){return jdbc.query("SELECT c.*,count(r.id) record_count FROM quality.data_category c LEFT JOIN quality.data_record r ON r.category_id=c.id AND r.deleted=false WHERE c.organization_id=? AND c.business_type=? GROUP BY c.id ORDER BY c.sort_order,c.created_at",(rs,n)->category(rs),org,type);}
    public Category category(UUID org,UUID id){var rows=jdbc.query("SELECT c.*,0 record_count FROM quality.data_category c WHERE organization_id=? AND id=?",(rs,n)->category(rs),org,id);if(rows.isEmpty())throw new ApiException(ApiErrorCode.NOT_FOUND,"品管分类不存在");return rows.getFirst();}
    public Category createCategory(UUID org,UUID user,String type,String name,String desc){try{var id=UUID.randomUUID();jdbc.update("INSERT INTO quality.data_category(id,organization_id,business_type,name,description,created_by) VALUES(?,?,?,?,?,?)",id,org,type,name,desc,user);return category(org,id);}catch(DuplicateKeyException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"分类名称已存在");}}
    public Category updateCategory(UUID org,UUID id,String name,String desc){try{if(jdbc.update("UPDATE quality.data_category SET name=?,description=?,updated_at=now() WHERE organization_id=? AND id=?",name,desc,org,id)==0)throw new ApiException(ApiErrorCode.NOT_FOUND,"品管分类不存在");return category(org,id);}catch(DuplicateKeyException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"分类名称已存在");}}
    public void deleteCategory(UUID org,UUID id){if(jdbc.queryForObject("SELECT count(*) FROM quality.data_record WHERE organization_id=? AND category_id=? AND deleted=false",Long.class,org,id)>0)throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"该分类下存在数据，请先移动或删除数据");jdbc.update("DELETE FROM quality.data_category WHERE organization_id=? AND id=?",org,id);}
    public PageResponse<RecordView> records(UUID org,String role,String type,UUID cat,String keyword,int page,int size){var like="%"+(keyword==null?"":keyword.trim())+"%";var where=" organization_id=? AND business_type=? AND deleted=false AND (?::uuid IS NULL OR category_id=?) AND (?='' OR business_no ILIKE ? OR data_jsonb::text ILIKE ?) AND (visibility='ALL' OR ? IN ('ADMIN','SYSTEM_ADMIN') OR (?='QUALITY_MANAGER' AND visibility IN ('QUALITY','PROJECT')) OR (? LIKE 'RND%' AND visibility='RND'))";var total=jdbc.queryForObject("SELECT count(*) FROM quality.data_record WHERE"+where,Long.class,org,type,cat,cat,keyword==null?"":keyword.trim(),like,like,role,role,role);var rows=jdbc.query("SELECT r.*,(SELECT name FROM quality.data_category c WHERE c.id=r.category_id) category_name,COALESCE((SELECT original_name FROM ops.file_object f WHERE f.id=r.source_file_id AND f.status <> 'DELETED'),(SELECT original_name FROM quality.upload_file u WHERE u.generated_record_id=r.id AND u.deleted=false ORDER BY u.created_at LIMIT 1)) source_file_name FROM quality.data_record r WHERE"+where+" ORDER BY updated_at DESC LIMIT ? OFFSET ?",(rs,n)->record(rs),org,type,cat,cat,keyword==null?"":keyword.trim(),like,like,role,role,role,size,(page-1)*size);return new PageResponse<>(rows,page,size,total,(total+size-1)/size);}
    public RecordView record(UUID org,UUID id){return record(org,"ADMIN",id);}
    public RecordView record(UUID org,String role,UUID id){var rows=jdbc.query("SELECT r.*,(SELECT name FROM quality.data_category c WHERE c.id=r.category_id) category_name,COALESCE((SELECT original_name FROM ops.file_object f WHERE f.id=r.source_file_id AND f.status <> 'DELETED'),(SELECT original_name FROM quality.upload_file u WHERE u.generated_record_id=r.id AND u.deleted=false ORDER BY u.created_at LIMIT 1)) source_file_name FROM quality.data_record r WHERE r.organization_id=? AND r.id=? AND r.deleted=false AND (r.visibility='ALL' OR ? IN ('ADMIN','SYSTEM_ADMIN') OR (?='QUALITY_MANAGER' AND r.visibility IN ('QUALITY','PROJECT')) OR (? LIKE 'RND%' AND r.visibility='RND'))",(rs,n)->record(rs),org,id,role,role,role);if(rows.isEmpty())throw new ApiException(ApiErrorCode.NOT_FOUND,"品管数据不存在");return rows.getFirst();}
    public List<VersionView> versions(UUID org,UUID recordId){return jdbc.query("SELECT v.*,coalesce(u.display_name,u.username,'未知用户') created_by_name FROM quality.data_record_version v LEFT JOIN iam.app_user u ON u.id=v.created_by WHERE v.organization_id=? AND v.record_id=? ORDER BY v.version_no DESC",(rs,n)->version(rs),org,recordId);}
    public RecordView upsert(UUID org,UUID user,String type,UUID cat,UUID id,String no,JsonNode data,JsonNode workbookSnapshot,long version){try{UUID recordId=id;if(id==null){recordId=UUID.randomUUID();jdbc.update("INSERT INTO quality.data_record(id,organization_id,business_type,category_id,business_no,data_jsonb,workbook_snapshot_jsonb,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?)",recordId,org,type,cat,no,pg(data),pgOrNull(workbookSnapshot),user,user);insertVersion(org,user,recordId,1,no,data,workbookSnapshot,0,"INITIAL");}else{var current=record(org,id);var next=versions(org,id).stream().mapToInt(VersionView::versionNo).max().orElse(0)+1;if(jdbc.update("UPDATE quality.data_record SET category_id=?,business_no=?,data_jsonb=?,workbook_snapshot_jsonb=?,updated_by=?,lock_version=lock_version+1,updated_at=now() WHERE id=? AND organization_id=? AND lock_version=? AND deleted=false",cat,no,pg(data),pgOrNull(workbookSnapshot),user,id,org,version)==0)throw new ApiException(ApiErrorCode.OPTIMISTIC_LOCK_CONFLICT,"品管数据已被其他用户修改");insertVersion(org,user,id,next,no,data,workbookSnapshot,current.lockVersion()+1,"EDIT");}return record(org,recordId);}catch(DuplicateKeyException e){throw new ApiException(ApiErrorCode.RESOURCE_CONFLICT,"编号不能为空或重复");}}
    public void insertVersion(UUID org,UUID user,UUID recordId,int versionNo,String no,JsonNode data,JsonNode workbookSnapshot,long lockVersion,String changeType){jdbc.update("INSERT INTO quality.data_record_version(id,organization_id,record_id,version_no,business_no,data_jsonb,workbook_snapshot_jsonb,lock_version,change_type,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),org,recordId,versionNo,no,pg(data),pgOrNull(workbookSnapshot),lockVersion,changeType,user);}
    public void softDelete(UUID org,List<UUID> ids){if(ids==null)return;ids.forEach(id->jdbc.update("UPDATE quality.data_record SET deleted=true,updated_at=now() WHERE organization_id=? AND id=?",org,id));}
    public void softDeleteOne(UUID org,UUID id){if(jdbc.update("UPDATE quality.data_record SET deleted=true,updated_at=now() WHERE organization_id=? AND id=? AND deleted=false",org,id)==0)throw new ApiException(ApiErrorCode.NOT_FOUND,"品管数据不存在");}
    public void move(UUID org,List<UUID> ids,UUID cat){if(ids==null)return;ids.forEach(id->jdbc.update("UPDATE quality.data_record SET category_id=?,lock_version=lock_version+1,updated_at=now() WHERE organization_id=? AND id=? AND deleted=false AND business_type=(SELECT business_type FROM quality.data_category WHERE organization_id=? AND id=?)",cat,org,id,org,cat));}
    public UUID insertDraft(UUID org,UUID user,String type,UUID cat,String no,JsonNode data,QualityDataService.UploadInput in){var id=UUID.randomUUID();jdbc.update("INSERT INTO quality.data_record(id,organization_id,business_type,category_id,business_no,data_jsonb,source_file_id,project_id,project_name,stage_id,stage_name,task_id,task_name,visibility,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,org,type,cat,no,pg(data),in.fileId(),in.projectId(),in.projectName(),in.stageId(),in.stageName(),in.taskId(),in.taskName(),in.visibility(),user,user);insertVersion(org,user,id,1,no,data,null,0,"UPLOAD");return id;}
    public VersionView publish(UUID org,UUID user,UUID id){var current=record(org,id);if("coa".equals(current.businessType())){jdbc.update("UPDATE quality.data_record SET data_jsonb=jsonb_set(data_jsonb,'{status}',to_jsonb('已签发'::text),true),lock_version=lock_version+1,updated_by=?,updated_at=now() WHERE organization_id=? AND id=? AND deleted=false",user,org,id);current=record(org,id);}var next=jdbc.queryForObject("SELECT coalesce(max(version_no),0)+1 FROM quality.data_record_version WHERE organization_id=? AND record_id=?",Integer.class,org,id);insertVersion(org,user,id,next,current.businessNo(),current.data(),current.workbookSnapshot(),current.lockVersion(),"PUBLISH");return versions(org,id).getFirst();}
    public UploadView insertUpload(UUID org,UUID user,UUID recordId,QualityDataService.UploadInput in){var id=UUID.randomUUID();jdbc.update("INSERT INTO quality.upload_file(id,organization_id,file_id,category_id,original_name,content_type,file_size,sha256,project_id,project_name,stage_id,stage_name,task_id,task_name,visibility,status,generated_record_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,org,in.fileId(),in.categoryId(),in.originalName(),in.contentType(),in.size(),in.sha256(),in.projectId(),in.projectName(),in.stageId(),in.stageName(),in.taskId(),in.taskName(),in.visibility(),"DRAFT_CREATED",recordId,user);return upload(org,id);}
    public Optional<UploadView> findUploadByHash(UUID org,String sha256){if(sha256==null||sha256.isBlank())return Optional.empty();var rows=jdbc.query("SELECT u.*,(SELECT name FROM quality.data_category c WHERE c.id=u.category_id) category_name FROM quality.upload_file u WHERE u.organization_id=? AND u.sha256=? AND u.deleted=false ORDER BY u.created_at LIMIT 1",(rs,n)->upload(rs),org,sha256);return rows.stream().findFirst();}
    public Optional<String> findBusinessNoByField(UUID org,String type,String field,String value){if(value==null||value.isBlank()||!List.of("batchNumber","productName","chemicalName","fileName").contains(field))return Optional.empty();var rows=jdbc.query("SELECT business_no FROM quality.data_record WHERE organization_id=? AND business_type=? AND deleted=false AND data_jsonb ->> ? = ? ORDER BY updated_at DESC LIMIT 1",(rs,n)->rs.getString("business_no"),org,type,field,value.trim());return rows.stream().findFirst();}
    public PageResponse<UploadView> uploads(UUID org,String role,String keyword,String status,UUID projectId,int page,int size){
        var q=keyword==null?"":keyword.trim();
        var like="%"+q+"%";
        var statusValue=status==null?"":status.trim();
        var where=" organization_id=? AND deleted=false AND (?='' OR original_name ILIKE ?) AND (?='' OR status=?) AND (?::uuid IS NULL OR project_id=?) AND (visibility='ALL' OR ? IN ('ADMIN','SYSTEM_ADMIN') OR (?='QUALITY_MANAGER' AND visibility IN ('QUALITY','PROJECT')) OR (? LIKE 'RND%' AND visibility='RND'))";
        var total=jdbc.queryForObject("SELECT count(*) FROM quality.upload_file WHERE"+where,Long.class,org,q,like,statusValue,statusValue,projectId,projectId,role,role,role);
        var rows=jdbc.query("SELECT u.*,(SELECT name FROM quality.data_category c WHERE c.id=u.category_id) category_name FROM quality.upload_file u WHERE"+where+" ORDER BY created_at DESC LIMIT ? OFFSET ?",
                (rs,n)->upload(rs),org,q,like,statusValue,statusValue,projectId,projectId,role,role,role,size,(page-1)*size);
        return new PageResponse<>(rows,page,size,total,(total+size-1)/size);
    }
    public void deleteUpload(UUID org,UUID id){jdbc.update("UPDATE quality.upload_file SET deleted=true WHERE organization_id=? AND id=?",org,id);}
    private UploadView upload(UUID org,UUID id){return jdbc.queryForObject("SELECT u.*,(SELECT name FROM quality.data_category c WHERE c.id=u.category_id) category_name FROM quality.upload_file u WHERE organization_id=? AND id=?",(rs,n)->upload(rs),org,id);}
    private Category category(ResultSet r)throws java.sql.SQLException{return new Category(r.getObject("id",UUID.class),r.getString("business_type"),r.getString("name"),r.getString("description"),r.getBoolean("system_default"),r.getInt("sort_order"),r.getLong("record_count"));}
    private RecordView record(ResultSet r)throws java.sql.SQLException{return new RecordView(r.getObject("id",UUID.class),r.getString("business_type"),r.getObject("category_id",UUID.class),r.getString("category_name"),r.getString("business_no"),json(r.getString("data_jsonb")),r.getObject("source_file_id",UUID.class),r.getString("source_file_name"),r.getObject("project_id",UUID.class),r.getString("project_name"),r.getString("stage_name"),r.getString("task_name"),r.getString("visibility"),jsonNullable(r.getString("workbook_snapshot_jsonb")),r.getLong("lock_version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());}
    private VersionView version(ResultSet r)throws java.sql.SQLException{return new VersionView(r.getObject("id",UUID.class),r.getObject("record_id",UUID.class),r.getInt("version_no"),r.getString("business_no"),json(r.getString("data_jsonb")),jsonNullable(r.getString("workbook_snapshot_jsonb")),r.getLong("lock_version"),r.getString("change_type"),r.getString("created_by_name"),r.getTimestamp("created_at").toInstant());}
    private UploadView upload(ResultSet r)throws java.sql.SQLException{return new UploadView(r.getObject("id",UUID.class),r.getObject("file_id",UUID.class),r.getObject("category_id",UUID.class),r.getString("category_name"),r.getString("original_name"),r.getString("content_type"),r.getLong("file_size"),r.getString("status"),r.getObject("generated_record_id",UUID.class),r.getObject("project_id",UUID.class),r.getString("project_name"),r.getString("stage_name"),r.getString("task_name"),r.getString("visibility"),r.getTimestamp("created_at").toInstant());}
    private JsonNode json(String s){try{return mapper.readTree(s);}catch(Exception e){return mapper.createObjectNode();}}
    private JsonNode jsonNullable(String s){if(s==null||s.isBlank())return null;return json(s);}
    private PGobject pg(JsonNode n){try{var p=new PGobject();p.setType("jsonb");p.setValue(n.toString());return p;}catch(Exception e){throw new IllegalStateException(e);}}
    private PGobject pgOrNull(JsonNode n){return n==null||n.isNull()?null:pg(n);}
}
