import { ArrowLeftOutlined, DeleteOutlined, DownloadOutlined, EditOutlined, LinkOutlined, SafetyCertificateOutlined, StopOutlined, UndoOutlined, UploadOutlined } from '@ant-design/icons';
import { Alert, App, Button, Descriptions, Empty, Input, Modal, Select, Space, Spin, Tag, Typography } from 'antd';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import { DocumentComparisonViewer, OriginalDocumentViewer, StructuredDocumentRenderer, VirtualDataTable } from '@/components/knowledge-document';
import { usePermission } from '@/components/auth/usePermission';
import { ProjectRelationPicker } from '@/components/project-relations/ProjectRelationPicker';
import { downloadPreviewFile } from '@/components/file-preview';
import { stageFile } from '@/services/files';
import { knowledgeApi, type KnowledgeDocument, type KnowledgeProcessing, type KnowledgeReview, type KnowledgeVersion, type Publication, type PublishedContent, type StructuredNode } from '@/services/knowledge';
import { projectResourceApi, type ProjectRelationTarget } from '@/services/project/project-resource-api';
import { pendingKnowledgeReviewPath } from './knowledge-document-routing';
import { documentWorkflowStatus } from './knowledge-workflow-status';

export function KnowledgeDocumentPage() {
  const { message, modal } = App.useApp(); const navigate = useNavigate(); const { id } = useParams<{ id: string }>();
  const [item, setItem] = useState<KnowledgeDocument>(); const [processing, setProcessing] = useState<KnowledgeProcessing>(); const [versions, setVersions] = useState<KnowledgeVersion[]>([]); const [review, setReview] = useState<KnowledgeReview>(); const [publications, setPublications] = useState<Publication[]>([]); const [publicationId, setPublicationId] = useState<string>(); const [published, setPublished] = useState<PublishedContent>(); const [publishedLoading, setPublishedLoading] = useState(false); const [publishedError, setPublishedError] = useState<string>(); const [publicationLoadAttempt, setPublicationLoadAttempt] = useState(0);
  const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [retrying, setRetrying] = useState(false); const [selectedSourceNodeKey, setSelectedSourceNodeKey] = useState<string>(); const fileInput = useRef<HTMLInputElement>(null);
  const [relationOpen, setRelationOpen] = useState(false); const [projectRelations, setProjectRelations] = useState<ProjectRelationTarget[]>([]);
  const canUpdate = usePermission('knowledge.update'); const canReview = usePermission('knowledge.review'); const canAssign = usePermission('project.assign');
  const load = useCallback(async (silent = false) => { if (!id) return; if (!silent) setLoading(true); try { const [document, history, released, process] = await Promise.all([knowledgeApi.get(id), knowledgeApi.versions(id), knowledgeApi.publications(id), knowledgeApi.processing(id)]); const current = released.find((value) => value.status === 'CURRENT'); setItem(document); setProjectRelations((document.relatedProjects || []).map((relation) => ({ projectId: relation.projectId, stageId: relation.stageId, taskId: relation.taskId }))); setProcessing(process); setVersions(history); setPublications(released); setPublicationId((value) => value && released.some((entry) => entry.id === value) ? value : current?.id); const reviewRequired = (canReview || canUpdate) && (document.reviewStatus === 'PENDING_REVIEW' || document.reviewStatus === 'REJECTED' || document.reviewRevisionStatus === 'BUILDING' || document.reviewRevisionStatus === 'FAILED' || document.status === 'FAILED' || document.status === 'PENDING_PROVIDER'); if (reviewRequired) { try { setReview(await knowledgeApi.review(id, document.currentVersionId)); } catch { setReview(undefined); } } else { setReview(undefined); } } catch (reason) { if (!silent) void message.error(reason instanceof Error ? reason.message : '文件详情加载失败'); } finally { if (!silent) setLoading(false); } }, [canReview, canUpdate, id, message]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (!review?.reviewRevision || review.reviewRevision.status !== 'BUILDING') return;
    const timer = window.setInterval(() => { void load(true); }, 3000);
    return () => window.clearInterval(timer);
  }, [load, review?.reviewRevision?.status]);
  useEffect(() => { if (!id || !publicationId) { setPublished(undefined); setPublishedLoading(false); setPublishedError(undefined); return; } let active = true; setPublished(undefined); setPublishedLoading(true); setPublishedError(undefined); void knowledgeApi.publishedContent(id, publicationId).then((value) => { if (active) setPublished(value); }).catch((reason) => { if (active) setPublishedError(reason instanceof Error ? reason.message : '发布内容加载失败'); }).finally(() => { if (active) setPublishedLoading(false); }); return () => { active = false; }; }, [id, publicationId, publicationLoadAttempt]);
  const directReviewPath = pendingKnowledgeReviewPath(canReview, item, review);
  useEffect(() => {
    if (!loading && directReviewPath) navigate(directReviewPath, { replace: true });
  }, [directReviewPath, loading, navigate]);
  const selectedPublication = publications.find((value) => value.id === publicationId); const sourceVersionId = selectedPublication?.versionId || item?.currentVersionId; const sourceVersion = versions.find((value) => value.id === sourceVersionId);
  const loadOriginal = useCallback(() => { if (!id) return Promise.reject(new Error('文档不存在')); return knowledgeApi.contentBlob(id, sourceVersionId); }, [id, sourceVersionId]);
  if (loading || !item || directReviewPath) return <div className="business-page"><Spin /></div>;

  const currentPublication = publications.find((value) => value.status === 'CURRENT'); const revisionStatus = review?.reviewRevision?.status; const reviewPending = Boolean(review && revisionStatus && revisionStatus !== 'PUBLISHED' && revisionStatus !== 'SUPERSEDED'); const pendingNewVersion = Boolean(review && (!currentPublication || review.versionId !== currentPublication.versionId || reviewPending)); const workflowStatus = documentWorkflowStatus(item);
  const uploadVersion = async (file?: File) => { if (!file || !item.categoryId) return; setUploading(true); try { const staged = await stageFile(file, 'KNOWLEDGE'); await knowledgeApi.preflight(staged.fileId, item.categoryId); await knowledgeApi.createGoverned({ fileId: staged.fileId, title: item.title, libraryScope: item.libraryScope, categoryId: item.categoryId, tags: review?.tags, resolution: 'NEW_VERSION', targetDocumentId: item.id, sourceInfo: { originalName: file.name, uploadContext: 'document-version' } }); void message.success('新版本已提交解析；当前发布版继续可检索'); await load(); } catch (reason) { void message.error(reason instanceof Error ? reason.message : '新版本上传失败'); } finally { setUploading(false); } };
  const download = async () => { const version = versions.find((value) => value.id === (published?.publication.versionId || item.currentVersionId)); const versionId = published?.publication.versionId || item.currentVersionId; try { await downloadPreviewFile({ fileName: version?.originalName || item.originalName, contentType: version?.contentType || item.contentType, size: version?.size || item.size, load: loadOriginal, downloadUrl: `/api/v1/knowledge/documents/${encodeURIComponent(item.id)}/versions/${encodeURIComponent(versionId)}/content` }); } catch (reason) { void message.error(reason instanceof Error ? reason.message : '下载失败'); } };
  const grant = (action: 'APPROVE' | 'REVOKE') => { modal.confirm({ title: action === 'APPROVE' ? '允许此文档用于 AI 问答？' : '撤销此文档的 AI 授权？', content: action === 'APPROVE' ? '授权覆盖该文档后续修订和新文件版本，直到主动撤销。' : '将取消待执行任务并清除已有向量，关键词检索不受影响。', okText: action === 'APPROVE' ? '确认授权' : '确认撤销', onOk: async () => { try { await knowledgeApi.grant(item.id, action); await load(); } catch (reason) { void message.error(reason instanceof Error ? reason.message : 'AI 授权操作失败'); throw reason; } } }); };
  const deleteDocument = () => { if (!item.allowedActions?.includes('DELETE')) return; modal.confirm({ title: `删除“${item.title}”？`, content: '仅删除未发布草稿及其解析结果。', okText: '确认删除', okButtonProps: { danger: true }, cancelText: '取消', onOk: async () => { await knowledgeApi.remove(item.id); void message.success('文档已删除'); navigate('/knowledge/view'); } }); };
  const changeLifecycle = () => { if (item.allowedActions?.includes('RESTORE')) { modal.confirm({ title: `恢复“${item.title}”？`, okText: '恢复', cancelText: '取消', onOk: async () => { await knowledgeApi.restore(item.id); await load(); } }); return; } if (!item.allowedActions?.includes('DISABLE')) return; let reason = ''; modal.confirm({ title: `停用“${item.title}”？`, content: <Input.TextArea placeholder="停用原因（必填）" onChange={(event) => { reason = event.target.value; }} />, okText: '确认停用', okButtonProps: { danger: true }, cancelText: '取消', onOk: async () => { if (!reason.trim()) throw new Error('停用原因不能为空'); await knowledgeApi.disable(item.id, reason.trim()); await load(); } }); };
  const retryParse = () => { if (!review) { void message.error('当前版本没有可重试的解析记录'); return; } modal.confirm({ title: '重新解析原文件？', content: '系统将使用当前统一解析策略重新处理该文件。', okText: '提交重新解析', onOk: async () => { setRetrying(true); try { await knowledgeApi.reparse(review); void message.success('已重新提交解析任务'); await load(); } finally { setRetrying(false); } } }); };
  const saveRelations = async () => { if (!id) return; setUploading(true); try { await projectResourceApi.replaceLinks('KNOWLEDGE_DOCUMENT', id, projectRelations.filter((relation) => relation.projectId)); setRelationOpen(false); await load(); void message.success('关联项目已保存'); } catch (reason) { void message.error(reason instanceof Error ? reason.message : '关联项目保存失败'); } finally { setUploading(false); } };
  const selectedTableId = published ? findTableForSource(published.confirmedDocument.content, selectedSourceNodeKey) : undefined;
  return <div className="business-page knowledge-document-view">
    <div className="business-page-heading"><Space><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/knowledge/view')}>返回知识库</Button><div><Typography.Title level={2} style={{ margin: 0 }}>{item.title}</Typography.Title><Typography.Text type="secondary">{currentPublication ? `当前发布 #${currentPublication.publicationNo}` : '尚未发布'} · 原文件与确认内容同屏查看</Typography.Text><div>{item.relatedProjects?.map((relation) => <Tag color="blue" key={`${relation.projectId}-${relation.stageId || ''}-${relation.taskId || ''}`} onClick={() => navigate(`/projects/${relation.projectId}`)} style={{ cursor: 'pointer' }}>{relation.projectName}{relation.stageName ? ` / ${relation.stageName}` : ''}{relation.taskName ? ` / ${relation.taskName}` : ''}</Tag>)}</div></div></Space><Space wrap>{canUpdate && <><input ref={fileInput} hidden type="file" onChange={(event) => { void uploadVersion(event.target.files?.[0]); event.currentTarget.value = ''; }} /><Button icon={<UploadOutlined />} loading={uploading} disabled={!item.categoryId} onClick={() => fileInput.current?.click()}>上传新版本</Button></>}{canReview && pendingNewVersion && revisionStatus !== 'BUILDING' && review?.reviewRevision && <Button type="primary" onClick={() => navigate(`/knowledge/review/${review.documentId}/${review.versionId}`)}>进入校对</Button>}{canUpdate && currentPublication && <Button icon={<EditOutlined />} onClick={() => navigate(`/knowledge/review/${item.id}/${currentPublication.versionId}?mode=revision`)}>修订内容</Button>}<Button icon={<DownloadOutlined />} onClick={() => void download()}>下载原文件</Button>{canUpdate && (item.aiStatus === 'APPROVED' ? <Button danger onClick={() => grant('REVOKE')}>撤销 AI</Button> : <Button icon={<SafetyCertificateOutlined />} disabled={!currentPublication} onClick={() => grant('APPROVE')}>授权 AI</Button>)}{canUpdate && canAssign && <Button icon={<LinkOutlined />} onClick={() => setRelationOpen(true)}>关联项目</Button>}{canUpdate && item.allowedActions?.includes('DELETE') ? <Button danger icon={<DeleteOutlined />} onClick={deleteDocument}>删除</Button> : null}{canUpdate && (item.allowedActions?.includes('DISABLE') || item.allowedActions?.includes('RESTORE')) ? <Button danger={item.allowedActions.includes('DISABLE')} icon={item.allowedActions.includes('DISABLE') ? <StopOutlined /> : <UndoOutlined />} onClick={changeLifecycle}>{item.allowedActions.includes('DISABLE') ? '停用' : '恢复'}</Button> : null}</Space></div>
    {item.lifecycleStatus === 'DISABLED' && <Alert type="warning" showIcon message="此文档已停用，当前发布版不参与检索" />}
    {revisionStatus === 'BUILDING' && <Alert type="info" showIcon message="正在发布，请稍候。页面会自动更新状态。" />}
    {revisionStatus === 'FAILED' && <Alert type="error" showIcon message={`发布失败：${review?.reviewRevision?.failureReason || '请进入校对页重试'}`} />}
    {review?.parseRun?.parserMode === 'AGENT_FALLBACK' && <Alert type="warning" showIcon message="当前待校对版本使用 Agent 降级解析，版面和坐标质量较低。" />}
    {item.status === 'FAILED' || item.status === 'PENDING_PROVIDER' || item.status === 'REJECTED' ? <Alert type="error" showIcon message={processing?.documentError || processing?.parseRunError || processing?.lastError || item.parseError || '文件解析失败'} description={`解析阶段：${processing?.currentStage || processing?.parseRunStatus || item.status} · 尝试 ${processing?.attemptCount || 0}/${processing?.maxAttempts || 0}`} action={canUpdate ? <Button loading={retrying} onClick={() => void retryParse()}>重新解析</Button> : undefined} /> : null}
    {pendingNewVersion && revisionStatus !== 'BUILDING' && revisionStatus !== 'FAILED' && <Alert type="info" showIcon message={`V${review?.versionNo} 正在等待校对；下方仍展示可检索的旧发布内容。`} />}
    {publications.length > 0 && <div className="knowledge-publication-switch"><Typography.Text type="secondary">查看发布历史</Typography.Text><Select value={publicationId} style={{ width: 220 }} onChange={(value) => { setPublicationId(value); setPublished(undefined); setSelectedSourceNodeKey(undefined); }} options={publications.map((value) => ({ value: value.id, label: `发布 #${value.publicationNo}${value.status === 'CURRENT' ? '（当前）' : ''}` }))} /></div>}
    {published ? <DocumentComparisonViewer original={<OriginalDocumentViewer fileName={published.originalName} contentType={published.contentType} load={loadOriginal} contentUrl={knowledgeApi.contentUrl(item.id, sourceVersionId)} sourceNodes={published.sourceNodes} selectedSourceNodeKey={selectedSourceNodeKey} onSourceSelect={setSelectedSourceNodeKey} />} result={<><StructuredDocumentRenderer value={published.confirmedDocument} selectedSourceNodeKey={selectedSourceNodeKey} onSourceSelect={(keys) => setSelectedSourceNodeKey(keys[0])} />{selectedTableId && <VirtualDataTable documentId={item.id} publicationId={published.publication.id} sourceTableId={selectedTableId} />}</>} resultTitle={`确认内容 · 发布 #${published.publication.publicationNo}`} /> : publicationId ? <DocumentComparisonViewer original={<OriginalDocumentViewer fileName={sourceVersion?.originalName || item.originalName} contentType={sourceVersion?.contentType || item.contentType} load={loadOriginal} contentUrl={knowledgeApi.contentUrl(item.id, sourceVersionId)} sourceNodes={[]} />} result={<div className="knowledge-viewer-state">{publishedLoading || !publishedError ? <><Spin /><span>正在加载发布内容</span></> : <Alert type="error" showIcon message="发布内容加载失败" description={publishedError} action={<Button onClick={() => setPublicationLoadAttempt((value) => value + 1)}>重新加载</Button>} />}</div>} /> : <DocumentComparisonViewer original={<OriginalDocumentViewer fileName={item.originalName} contentType={item.contentType} load={loadOriginal} contentUrl={knowledgeApi.contentUrl(item.id, sourceVersionId)} sourceNodes={[]} />} result={<div className="knowledge-viewer-state"><Empty description={revisionStatus === 'BUILDING' ? '正在发布，请稍候' : '尚未发布，普通阅读者不可查看校对草稿'} /></div>} />}
    <details className="knowledge-document-metadata"><summary>文件与发布信息</summary><Descriptions column={{ xs: 1, sm: 2, md: 4 }}><Descriptions.Item label="文件版本">V{published ? versions.find((value) => value.id === published.publication.versionId)?.versionNo : item.currentVersionNo}</Descriptions.Item><Descriptions.Item label="分类">{item.categoryName || '未分类'}</Descriptions.Item><Descriptions.Item label="状态"><Tag color={workflowStatus.color}>{workflowStatus.label}</Tag></Descriptions.Item><Descriptions.Item label="AI"><Tag color={item.aiStatus === 'APPROVED' ? 'green' : 'gold'}>{item.aiStatus}</Tag></Descriptions.Item><Descriptions.Item label="标签"><Space wrap>{review?.tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}</Space></Descriptions.Item></Descriptions></details>
    <Modal open={relationOpen} title="维护知识文档关联项目" width={760} okText="保存" confirmLoading={uploading} onCancel={() => setRelationOpen(false)} onOk={() => void saveRelations()}><ProjectRelationPicker value={projectRelations} onChange={setProjectRelations} /></Modal>
  </div>;
}

function findTableForSource(nodes: StructuredNode[] | undefined, sourceNodeKey?: string): string | undefined { if (!sourceNodeKey) return undefined; for (const node of nodes || []) { const sources = Array.isArray(node.attrs?.sourceNodeKeys) ? node.attrs.sourceNodeKeys : []; if (node.type === 'dataTableRef' && sources.includes(sourceNodeKey) && typeof node.attrs?.sourceTableId === 'string') return node.attrs.sourceTableId; const nested = findTableForSource(node.content, sourceNodeKey); if (nested) return nested; } return undefined; }
